default:
  image: pipelinecomponents/markdownlint:latest

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

stages:
  - lint

lint:
  stage: lint
  script:
    - mdl --style markdownlint.rb --warnings .